# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\mingw64\CLion 2018.2.3\bin\cmake\win\bin\cmake.exe"

# The command to remove a file.
RM = "C:\mingw64\CLion 2018.2.3\bin\cmake\win\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\mingw64\CLionProjects\Assembler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\mingw64\CLionProjects\Assembler\cmake-build-debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"C:\mingw64\CLion 2018.2.3\bin\cmake\win\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\mingw64\CLion 2018.2.3\bin\cmake\win\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\mingw64\CLionProjects\Assembler\cmake-build-debug\CMakeFiles C:\mingw64\CLionProjects\Assembler\cmake-build-debug\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\mingw64\CLionProjects\Assembler\cmake-build-debug\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ASM

# Build rule for target.
ASM: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ASM
.PHONY : ASM

# fast build rule for target.
ASM/fast:
	$(MAKE) -f CMakeFiles\ASM.dir\build.make CMakeFiles/ASM.dir/build
.PHONY : ASM/fast

#=============================================================================
# Target rules for targets named VM

# Build rule for target.
VM: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 VM
.PHONY : VM

# fast build rule for target.
VM/fast:
	$(MAKE) -f CMakeFiles\VM.dir\build.make CMakeFiles/VM.dir/build
.PHONY : VM/fast

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) -f CMakeFiles\check.dir\build.make CMakeFiles/check.dir/build
.PHONY : check/fast

ASM.obj: ASM.c.obj

.PHONY : ASM.obj

# target to build an object file
ASM.c.obj:
	$(MAKE) -f CMakeFiles\ASM.dir\build.make CMakeFiles/ASM.dir/ASM.c.obj
.PHONY : ASM.c.obj

ASM.i: ASM.c.i

.PHONY : ASM.i

# target to preprocess a source file
ASM.c.i:
	$(MAKE) -f CMakeFiles\ASM.dir\build.make CMakeFiles/ASM.dir/ASM.c.i
.PHONY : ASM.c.i

ASM.s: ASM.c.s

.PHONY : ASM.s

# target to generate assembly for a file
ASM.c.s:
	$(MAKE) -f CMakeFiles\ASM.dir\build.make CMakeFiles/ASM.dir/ASM.c.s
.PHONY : ASM.c.s

VM.obj: VM.c.obj

.PHONY : VM.obj

# target to build an object file
VM.c.obj:
	$(MAKE) -f CMakeFiles\VM.dir\build.make CMakeFiles/VM.dir/VM.c.obj
.PHONY : VM.c.obj

VM.i: VM.c.i

.PHONY : VM.i

# target to preprocess a source file
VM.c.i:
	$(MAKE) -f CMakeFiles\VM.dir\build.make CMakeFiles/VM.dir/VM.c.i
.PHONY : VM.c.i

VM.s: VM.c.s

.PHONY : VM.s

# target to generate assembly for a file
VM.c.s:
	$(MAKE) -f CMakeFiles\VM.dir\build.make CMakeFiles/VM.dir/VM.c.s
.PHONY : VM.c.s

check.obj: check.c.obj

.PHONY : check.obj

# target to build an object file
check.c.obj:
	$(MAKE) -f CMakeFiles\check.dir\build.make CMakeFiles/check.dir/check.c.obj
.PHONY : check.c.obj

check.i: check.c.i

.PHONY : check.i

# target to preprocess a source file
check.c.i:
	$(MAKE) -f CMakeFiles\check.dir\build.make CMakeFiles/check.dir/check.c.i
.PHONY : check.c.i

check.s: check.c.s

.PHONY : check.s

# target to generate assembly for a file
check.c.s:
	$(MAKE) -f CMakeFiles\check.dir\build.make CMakeFiles/check.dir/check.c.s
.PHONY : check.c.s

mainFunctions.obj: mainFunctions.c.obj

.PHONY : mainFunctions.obj

# target to build an object file
mainFunctions.c.obj:
	$(MAKE) -f CMakeFiles\ASM.dir\build.make CMakeFiles/ASM.dir/mainFunctions.c.obj
	$(MAKE) -f CMakeFiles\VM.dir\build.make CMakeFiles/VM.dir/mainFunctions.c.obj
	$(MAKE) -f CMakeFiles\check.dir\build.make CMakeFiles/check.dir/mainFunctions.c.obj
.PHONY : mainFunctions.c.obj

mainFunctions.i: mainFunctions.c.i

.PHONY : mainFunctions.i

# target to preprocess a source file
mainFunctions.c.i:
	$(MAKE) -f CMakeFiles\ASM.dir\build.make CMakeFiles/ASM.dir/mainFunctions.c.i
	$(MAKE) -f CMakeFiles\VM.dir\build.make CMakeFiles/VM.dir/mainFunctions.c.i
	$(MAKE) -f CMakeFiles\check.dir\build.make CMakeFiles/check.dir/mainFunctions.c.i
.PHONY : mainFunctions.c.i

mainFunctions.s: mainFunctions.c.s

.PHONY : mainFunctions.s

# target to generate assembly for a file
mainFunctions.c.s:
	$(MAKE) -f CMakeFiles\ASM.dir\build.make CMakeFiles/ASM.dir/mainFunctions.c.s
	$(MAKE) -f CMakeFiles\VM.dir\build.make CMakeFiles/VM.dir/mainFunctions.c.s
	$(MAKE) -f CMakeFiles\check.dir\build.make CMakeFiles/check.dir/mainFunctions.c.s
.PHONY : mainFunctions.c.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... ASM
	@echo ... VM
	@echo ... check
	@echo ... rebuild_cache
	@echo ... ASM.obj
	@echo ... ASM.i
	@echo ... ASM.s
	@echo ... VM.obj
	@echo ... VM.i
	@echo ... VM.s
	@echo ... check.obj
	@echo ... check.i
	@echo ... check.s
	@echo ... mainFunctions.obj
	@echo ... mainFunctions.i
	@echo ... mainFunctions.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

